name: ecg_hand
description: "ECG Hand - Mobile companion app for Every Card Game Table"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Networking
  http: ^1.0.0
  web_socket_channel: ^3.0.0
  
  # Logging
  logging: ^1.2.0
  
  # State management
  provider: ^6.1.1
  
  # JSON handling  
  json_annotation: ^4.8.1
  
  # Path handling
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
